name: C build

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
        token: ${{ secrets.GitHub_PAT }}
    - name: make
      run: make
